version: '3.8'
services:
    front:
        container_name: front
        build:
            context: ./front
            dockerfile: ./Docker/Dockerfile
        ports:
            - "7172:80"
        depends_on:
            - db
            - back
    back:
        container_name: back
        build:
            context: ./back
            dockerfile: ./Docker/Dockerfile
        ports:
            - "7171:80"
        depends_on:
            - db
    db:
        container_name: db
        image: mysql
        restart: always
        volumes:
            - ./Docker/mysql/Sample.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
#        ports:
#            - "9906:3306"
